# service for unigraduate
#
apiVersion: v1
kind: Service
metadata:
  namespace: unigraduate
  name: unigraduate
  labels:
    app: unigraduate

spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: unigraduate
