# service for unigraduate
#
apiVersion: v1
kind: Service
metadata:
  namespace: unigraduate
  name: unigraduate
  labels:
    app: unigraduate
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    app: unigraduate
