apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unigraduate
  namespace: argocd

spec:
  destination:
    namespace: unigraduate
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/waseemtannous/UniGraduate.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
